# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6156c5a474d1daad1d759ae1447f8c82adc0c3f92d1f2cb71451b7caca7b839cce91e649546276652965c3b4b3ab9ddfe76329d44ed6727dcc48b7edd596accc

test:
  secret_key_base: de93c8b223da33e0cd7cecd2c81e440b6ec00b08c4aa90b9e5901f4f53957e478157e1987be3c1a437c822340af853f12535320ab125d170f727974655aa119b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
